name: New issue
description: Please review troubleshooting steps before submitting
body:
  - type: markdown
    attributes:
      value: |
        # 🔧 Troubleshooting Checklist

        Please go through the relevant section **before opening an issue**.
        Many common problems are resolved by these steps.

        ---

        ⚠️ **Known issue**: Installing on **Fedora** is currently problematic. It is recommended to use a **Debian-based** distribution or the **PSBBN Launcher for Windows**.

        1. Make sure you are running the latest version of your operating system and all updates are installed
        2. Use a recommended OS. The **PSBBN Definitive Project** has been fully tested on:
        - Debian
        - Linux Mint
        - Raspberry Pi OS
        - Windows 10 Home Edition
        - Windows 11 Home Edition

        ## Problems Running the Script

        **If you are using Windows and experience issues:**
        1. Open PowerShell as an administrator and run the following command:
        ```
        wsl --unregister PSBBN
        ```
        2. Download the latest version of the `PSBBN-Launcher-For-Windows.ps1` script [here](https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/releases/download/latest/PSBBN-Launcher-For-Windows.ps1)
        3. Ensure you have an active internet connection. If you are using a VPN, try disabling it
        4. Run the `PSBBN-Launcher-For-Windows.ps1` script again

        **If you are using Linux and experience issues:**
        1. Delete the `PSBBN-Definitive-Project` folder
        2. Re-Clone the repository with the following command:
        ```
        git clone https://github.com/CosmicScale/PSBBN-Definitive-Project.git
        ```

        **Still having issues?**
        1. Try connecting the PS2 drive directly to your PC using an internal SATA connection or a USB port directly on the motherboard. Avoid using add-on cards
        2. If you are using a SATA to USB adapter, try using a different make or model
        3. If you still have issues, try a different drive

        ## Problems Launching PSBBN and HOSDMenu
        When you connect the drive to your PS2 console and power it on, **PSBBN** or **HOSDMenu** should automatically launch.

        If your console boots to the regular OSD or freezes, it means that your drive has not been recognised or you are experiencing a hardware issue. You should check the following:
        1. Remove all PS2 Memory Cards from your console
        2. If you installed **PSBBN**, make sure you are using an **official Sony Network Adapter**; PSBBN does not support 3rd-party HDD adapters
        3. Check that the connectors on the console and network or HDD adapter are clean and free of dust/debris
        4. Ensure the network or HDD adapter and drive are securely connected to the console
        5. If using a SATA mod, make sure it has been installed correctly
        6. Try installing to a different drive
        7. If your console has an IDE converter or SATA mod installed, try using a different converter/mod.
        8. Try using a different official Sony Network Adapter or 3rd-party HDD adapter
        9. Try a different PS2 console

        ## Problems Launching Games

        If OPL freezes at startup, delete any existing OPL configuration files from your PS2 Memory Cards or connected USB devices. You can also hold `START` while OPL launches to bypass reading the configuration file.

        To display the games list in OPL, adjust the following settings:
        1. Settings > HDD (APA) Start Mode: Off
        2. Settings > BDM Start Mode: Auto
        3. Settings > BDM Devices > HDD (GPT/MBR): On
        4. Settings > Save Changes

        If games do not appear in the games list in NHDDL or OPL (after modifying the OPL settings as described above):
        1. Try connecting the PS2 drive directly to your PC using an internal SATA connection or a different SATA to USB adapter. Then reinstall PSBBN or HOSDMenu
        2. Try using a different drive and then reinstall PSBBN or HOSDMenu

        If games fail to launch from the PSBBN Game Collection or HOSDMenu, try the following:
        1. If you have a mod chip, disable it
        2. Remove all PS2 Memory Cards from your console
        3. Check that the connectors on the console and network or HDD adapter are clean and free of dust/debris
        4. Ensure the network or HDD adapter and drive are securely connected to the console
        5. If using a SATA mod, make sure it has been installed correctly
        6. Re-run the Game Installer and select the alternative game launcher (OPL or NHDDL)
        7. If your console has an IDE converter or SATA mod installed, try using a different converter/mod.
        8. Try using a different official Sony Network Adapter or 3rd-party HDD adapter
        9. Try a different PS2 console

        ---

        ✅ **If you have tried the relevant steps and the issue persists, continue below.**
  - type: textarea
    id: issue
    attributes:
      label: Describe the issue
      description: Include relevant logs (setup.log, PSBBN-installer.log, hosdmenu.log, game-installer.log, extras.log) OS, hardware details, and what you already tried.
    validations:
      required: true
